server:
  port: 9080

eureka:
  instance:
#    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://192.168.1.105:9080/eureka/,http://192.168.1.112:9080/eureka/

spring:
  application:
    name: eurka-server
